# Débuter avec la bibliothèque numpy

<div style="width: 50%; margin: 0 auto;">
    <img src="../images/logos/numpy.svg" alt="Numpy" style="width: 100%; height: auto;">
</div>

NumPy (Num erical Py thon) est une bibliothèque open-source très populaire pour Python, qui offre des fonctionnalités puissantes pour effectuer des opérations mathématiques et numériques. Elle est largement utilisée dans le domaine de l'apprentissage automatique, l'analyse de données, les simulations scientifiques, et bien d'autres domaines nécessitant des calculs numériques efficaces.

Pour utiliser NumPy, vous pouvez installer la bibliothèque en exécutant la commande "**pip install numpy**" dans votre terminal ou invite de commande.

Une fois NumPy installé, vous pouvez importer la bibliothèque dans votre code Python en utilisant **import numpy as np**, ce qui est une pratique courante pour raccourcir le nom de la bibliothèque et faciliter l'utilisation.

Ci-dessous, vous trouverez quelques exemples illustrant l'utilisation de la bibliothèque 

### Créer un tableau NumPy

Création de tableau simple

In [3]:
import numpy as np
#Création d'un tableau d'entier
tab=np.array([1,5,6,3])
print(tab)

# Création d'un tableau de réels
tab=np.array([1.,5.,6.,3.])
print(tab)

# Création d'un tableau de réels
tab=np.array([1,5,6,3],dtype=np.float32)
print(tab)



[1 5 6 3]
[1. 5. 6. 3.]
[1. 5. 6. 3.]


Crée un tableau de zéro avec une taille spécifiée

In [4]:
import numpy as np

taille = 5
tableau_vide = np.zeros(taille)

print(tableau_vide)

[0. 0. 0. 0. 0.]


Crée un tableau rempli de 1 avec une taille spécifiée.

In [5]:
import numpy as np

taille = 4
tableau_de_1 = np.ones(taille)

print(tableau_de_1)
# Résultat : [1. 1. 1. 1.]


[1. 1. 1. 1.]


 Crée un tableau rempli de valeurs identiques avec une taille spécifiée.

In [6]:
import numpy as np

taille = (4,3)
valeur = 7
tableau_valeurs_identiques = np.full(taille, valeur)

print(tableau_valeurs_identiques)
# Résultat : [[7 7 7]
# [7 7 7]
# [7 7 7]
# [7 7 7]]

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


Crée un tableau d'entiers entre une valeur de début et une valeur de fin, avec un pas spécifié.

In [7]:
import numpy as np

debut = 1
fin = 10
pas = 2
tableau_intervalles = np.arange(debut, fin, pas)

print(tableau_intervalles)
# Résultat : [1 3 5 7 9]


[1 3 5 7 9]


Crée un tableau linéairement espacé avec un nombre spécifié de valeurs entre un début et une fin.

In [8]:
import numpy as np

debut = 0
fin = 1
nombre_valeurs = 5
tableau_linspace = np.linspace(debut, fin, nombre_valeurs)

print(tableau_linspace)
# Résultat : [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


Création d'un tableau de valeur aléatoire

In [9]:
# Création d'un tableau de valeur aléatoire
tab=np.random.rand(3,5)
print(tab)


[[0.20244587 0.86232026 0.36175773 0.74288703 0.59474843]
 [0.22568399 0.43230712 0.38117919 0.98699938 0.2851022 ]
 [0.38142003 0.03810212 0.61705482 0.34026801 0.65326149]]


Création d'un tableau à partir d'une liste

In [11]:
import numpy as np

# Créer un tableau à partir d'une liste
liste = [1, 2, 3, 4, 5]
tableau = np.array(liste)

print(tableau)

[1 2 3 4 5]
[0.2 0.4 0.6 0.8 1. ]


### Opérations avec les tableaux NumPy 

In [15]:
import numpy as np

# Créer deux tableaux
tableau1 = np.array([1, 2, 3])
tableau2 = np.array([4, 5, 6])
print("tableau1:", tableau1)
print("tableau2:", tableau2)

# Addition de deux tableaux
somme = tableau1 + tableau2
print("Somme t1+t2:", somme)

# Multiplication élément par élément
produit = tableau1 * tableau2
print("Produit t1xt2:", produit)

# Opérations mathématiques avec un tableau
resultat = np.sqrt(tableau1) + np.sin(tableau2)
print("Résultat sqrt(t1)+sin(t2):", resultat)

division = tableau1 / 3
print("t1/3 :", division)

tableau1: [1 2 3]
tableau2: [4 5 6]
Somme t1+t2: [5 7 9]
Produit t1xt2: [ 4 10 18]
Résultat sqrt(t1)+sin(t2): [0.2431975  0.45528929 1.45263531]
t1/3 : [0.33333333 0.66666667 1.        ]


### Opération sur les matrices

Extraire la partie supérieure de la matrice

In [1]:
import numpy as np

# Création d'une matrice 4x4 pour illustrer les fonctions triu et tril
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

print(matrice)

matrice_triu = np.triu(matrice)

print("Partie supérieur de la matrice:",matrice_triu,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Partie supérieur de la matrice: [[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]] 



Extraire la partie inférieure de la matrice

In [3]:
import numpy as np

# Création d'une matrice 4x4 pour illustrer les fonctions triu et tril
matrice = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12],
                    [13, 14, 15, 16]])

print(matrice)

matrice_tril = np.tril(matrice)

print("Partie inférieur de la matrice:",matrice_tril,"\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Partie inférieur de la matrice: [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]] 



### Indexation et découpage de tableaux NumPy 

In [10]:
import numpy as np

# Créer un tableau
tableau = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Accéder à un élément spécifique
element = tableau[2]
print("Élément à l'index 2 :", element)

# Découper le tableau

tab_2_5 = tableau[1:5]
print("Sous-tableau du deuxième élément au cinquième élément:", tab_2_5)
# Accéder aux 3 premiers éléments
tab_3_premier = tableau[:3]
print("Trois premiers éléments ::", tab_3_premier)
# Accéder aux 3 derniers éléments
tab_3_dernier = tableau[-3:]
print("Trois derniers éléments :", tab_3_dernier)

Élément à l'index 2 : 30
Sous-tableau du deuxième élément au cinquième élément: [20 30 40 50]
Trois premiers éléments :: [10 20 30]
Trois derniers éléments : [70 80 90]


### Dimensions et formes de tableaux NumPy 

In [11]:
import numpy as np

# Créer un tableau 2D (matrice)
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Afficher le nombre de dimensions
print("Nombre de dimensions :", matrice.ndim)

# Afficher la forme (nombre de lignes et de colonnes)
print("Forme de la matrice :", matrice.shape)

# Accéder à un élément spécifique dans la matrice
element = matrice[1, 2]  # Deuxième ligne, troisième colonne
print("Élément à la position (1, 2) :", element)


Nombre de dimensions : 2
Forme de la matrice : (3, 3)
Élément à la position (1, 2) : 6


In [12]:
import numpy as np
tr = np.arange(20)
print("Notre tableau:\n",tr)
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
#        17, 18, 19])
# Réordonne le tableau en une matrice à 4 lignes et 5 colonnes
print("reshape (4,5):\n",tr.reshape(4,5))
# Réordonne le tableau en une matrice à 2 lignes et 10 colonnes
print("reshape (2,10):\n",tr.reshape(2,10))
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
print("reshape (20):\n",tr.reshape(20))
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
#       17, 18, 19])

Notre tableau:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshape (4,5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
reshape (2,10):
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
reshape (20):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### Fonctions statistiques avec NumPy 

In [13]:
import numpy as np

# Créer un tableau de valeurs aléatoires
tableau = np.random.randint(1, 100, size=10)

# Afficher le tableau
print("Tableau :", tableau)

# Calculer la moyenne
moyenne = np.mean(tableau)
print("Moyenne :", moyenne)

# Calculer la somme
somme = np.sum(tableau)
print("Somme :", somme)

# Trouver la valeur maximale et minimale
max_value = np.max(tableau)
min_value = np.min(tableau)
print("Valeur maximale :", max_value)
print("Valeur minimale :", min_value)


Tableau : [83 90 90 19 50 57 67 51 16 19]
Moyenne : 54.2
Somme : 542
Valeur maximale : 90
Valeur minimale : 16


# Exercices

### Opérations sur les tableaux

1. Créez deux tableaux NumPy à une dimension, A et B, contenant respectivement les nombres de 1 à 5 et de 6 à 10.
2. Additionnez les deux tableaux A et B.
3. Multipliez chaque élément du tableau A par 3.

### Manipulation de tableaux multidimensionnels

1. Créez une matrice NumPy 3x3 contenant des nombres entiers de 1 à 9.
2. Affichez la somme de chaque colonne.
3. Trouvez la valeur minimale et maximale dans la matrice.

### Indexation et tranchage

1. Créez un tableau NumPy contenant les carrés des entiers de 0 à 9.
2. Affichez les éléments pairs du tableau.
3. Créez une sous-matrice 2x2 à partir de la matrice créée à l'exercice précédent, en utilisant l'indexation.